test build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -85,7 +85,9 @@ jobs:
       run: |
        git checkout master # Make sure we are on master branch
        echo "Replacing RELEASE_URL in README.md with ${{ env.RELEASE_URL }}"
-       sed -i "s|Download latest build:.*|Download latest build: [Download Latest Build]('${RELEASE_URL}')|" README.md # Replace line with new JAR link
+       sed -i "s|RELEASE_URL|$RELEASE_URL|g" README.md
+       echo "README preview:"
+       grep 'Download Latest Build' README.md || echo "❌ Link not found"
        # Replace line with new JAR link
        git config --global user.name 'github-actions[bot]' # Set commit username
        git config --global user.email 'github-actions[bot]@users.noreply.github.com' # Set commit email
